### ISSUE TITLE
MacOS Applescript version

### ISSUE THREAD

**Issue by rbreaves** [tiaanv/SBKA#1]
Weird that we both rewrote this app from the same blog post within hours of each other..

Any ways here is an Applescript version of this that I bundled via the Applescript export feature - just had to drop the tone.wav file into the soundstandby.app/Resources/ location and it works. App has to be force quit as I have not bothered with whatever closes it properly on macOS.

```
set wavFileName to "tone.wav"
set wavFilePath to (path to resource wavFileName)

-- Repeat the loop indefinitely
repeat
	-- Play the .wav file
	do shell script "afplay " & quoted form of POSIX path of wavFilePath
	
	-- Wait for 10 minutes (600 seconds)
	delay 600
end repeat
```

And without the bundling, if someone want to just run the script and file in the same directory.
```
set scriptPath to (path to me as text)
set scriptFolder to (do shell script "dirname " & quoted form of POSIX path of scriptPath)
set wavFileName to "tone.wav"
set wavFilePath to scriptFolder & "/" & wavFileName

-- Repeat the loop indefinitely
repeat
    -- Play the .wav file
    do shell script "afplay " & quoted form of POSIX path of wavFilePath
    
    -- Wait for 10 minutes (600 seconds)
    delay 600
end repeat
```

**Comment by tiaanv** [comment]
I'll keep this pinned for a while if anyone is looking for a macOS option,
