### ISSUE TITLE
Choose audio output device (Not default)

### ISSUE THREAD

**Issue by donkeyhigh** [tiaanv/SBKA#2]
Hi.
Great work.
Any way to make it still pulse the audio on my speakers while I'm playing games with my headset (changed from Speakers to Headset in Windows)?

 - donkey

**Comment by tiaanv** [comment]
Yes.  Will implement some settings, and allow you to choose the sound device on which audio is monitored and played.

**Comment by tiaanv** [comment]
https://github.com/tiaanv/SBKA/releases/tag/V1.1.0
Enjoy!
