### ISSUE TITLE
Lower intervals

### ISSUE THREAD

**Issue by mindtrapper** [tiaanv/SBKA#3]
Please provide setting for setting interval under 1 minute. As you might have read in the discussions about your inspiration program, there are soundbars that go in standby with a "pop" sound in mere seconds. I have timed my Creative Stage V2 at 16 seconds.

Thank you!

**Comment by tiaanv** [comment]
I have changed the settings to now be in seconds:

Published in this release:
https://github.com/tiaanv/SBKA/releases/tag/V1.2.1
