### ISSUE TITLE
Disable when locked

### ISSUE THREAD

**Issue by EarMaster** [tiaanv/SBKA#4]
It would be a great addition to be able to disable the sound when the screen is locked. When I lock my screen I am totally fine with my speaker going to standby I only want it to be constantly available when I'm actually in front of my machine. This may not be true for everyone so it should be an optional feature.

**Comment by tiaanv** [comment]
It should be easy enough to do.  The only issue with this approach is that (in my case) once the soundbar goes off It has to be switched on manually.  So even if the app sends sound it will have no effect.

**Comment by tiaanv** [comment]
https://github.com/tiaanv/SBKA/releases/tag/v1.4.0
Added detection of locked station.

**Comment by EarMaster** [comment]
Thank you for this great tool and for your fast implementation of this feature.
